### ISSUE TITLE
`@media (width >= 500px)` stripped

### ISSUE THREAD

**Issue by bennypowers** [divriots/jampack#69]
media queries using [range context syntax](https://drafts.csswg.org/mediaqueries/#range-context) are getting stripped

in (index.css) 
```css
@media (width >= 500px) {
  h1 { font-size: 2em; }
}
```
```
bennypowers.dev on  decks/brno/content [$!?] via  v18.16.0 
❯ cat _site/index.css | grep media                                                                                                                                (base) 
```
